"""Pydantic schemas for agent run responses."""

from pydantic import BaseModel, Field


class AgentRunResponse(BaseModel):
    """Response returned after executing the Reason → Plan → Act → Observe pipeline."""

    workflow_id: str = Field(
        ...,
        description="Unique identifier of the workflow.",
    )

    intent: str = Field(
        ...,
        description="Intent detected by the Reason node.",
    )

    plan: list[str] = Field(
        ...,
        description="Ordered execution plan generated by the Plan node.",
    )

    final_response: str | None = Field(
        None,
        description="Final natural-language response generated by the Observe node.",
    )

    status: str = Field(
        ...,
        description="Workflow status (RUNNING, COMPLETED, FAILED).",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "workflow_id": "6c3f8d8b-8c0d-4d7e-a89d-6d7d9b6f7f5e",
                "intent": "research AI agents",
                "plan": [
                    "Search information about AI agents",
                    "Summarize key findings",
                    "Prepare the final response",
                ],
                "final_response": (
                    "AI agents are autonomous systems that can reason, "
                    "plan, and use tools to accomplish tasks."
                ),
                "status": "COMPLETED",
            }
        }
    }